### ISSUE TITLE
json logs sent as is

### ISSUE THREAD

**Issue by fduranti** [vmware/fluent-plugin-vmware-loginsight#16]
I'm trying to configure fluentd to send kubernetes log from vsphere 7 tanzukubernetescluster to loginsight (8.1.1).
I was able to configure it and send logs but I'm not sure if there's any way to get the logs in a better format.
I have some application that send out json logs.
Reading the documentation of this plugin it seems that it should flatten (flatten_hashes) and send fields from a json log to loginsight but I see them sent as is:
This is for example image:
![image](https://user-images.githubusercontent.com/1173084/90271566-4ee1cd80-de5c-11ea-9f24-44714cc6ca73.png)

This is the log message I get:
```
{"transaction":{"client_ip":"127.0.0.1","time_stamp":"Fri Aug 14 16:22:42 2020","server_id":"7199d4814af1907f628166312cfa622874c5a06b","client_port":52598,"host_ip":"127.0.0.1","host_port":10246,"unique_id":"159742216256.485092","request":{"method":"GET","http_version":1.1,"uri":"/is-dynamic-lb-initialized","headers":{"Host":"127.0.0.1:10246","User-Agent":"Go-http-client/1.1","Accept-Encoding":"gzip"}},"response":{"body":"OK\n","http_code":200,"headers":{"Server":"nginx/1.17.7","Date":"Fri, 14 Aug 2020 16:22:42 GMT","Content-Type":"text/html","Connection":"close"}},"producer":{"modsecurity":"ModSecurity v3.0.3 (Linux)","connector":"ModSecurity-nginx v1.0.1","secrules_engine":"DetectionOnly","components":["OWASP_CRS/3.2.0\""]},"messages":[{"message":"Host header is a numeric IP address","details":{"match":"Matched \"Operator `Rx' with parameter `^[\\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `127.0.0.1:10246' )","reference":"o0,15v46,15","ruleId":"920350","file":"/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf","lineNumber":"678","data":"127.0.0.1:10246","severity":"4",&quot;ver":"OWASP_CRS/3.2.0","rev":"","tags":["application-multi","language-multi","platform-multi","attack-protocol","OWASP_CRS","OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST","WASCTC/WASC-21","OWASP_TOP_10/A7","PCI/6.5.10"],"maturity":"0","accuracy":"0"}}]}}
```

There's any simple way or can someone help me on how to get logs in a better way?

Thanks

**Comment by toddc-vmware** [comment]
use a filter parser with format json, something like :

<filter docker.**>
  @type parser
  format json
  key_name log
  inject_key_prefix log
</filter>

**Comment by mohitevishal** [comment]
Closing as this could be fixed with some formatting
